language: python
python:
  - 2.7

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH

install:
  - conda update -q --yes conda
  - conda install -q --yes numpy scipy matplotlib nose
  - conda install -q --yes -c https://conda.binstar.org/osgeo gdal
  - export GDAL_DATA=/home/vagrant/miniconda/share/gdal/
  - export GEOS_DIR=/home/vagrant/miniconda/
  - pip install -q basemap --allow-external basemap --allow-unverified basemap
  - python -c 'import gdal; print gdal.__file__'
  - python -c 'from mpl_toolkits.basemap import Basemap'
  - pip install coveralls
#- python setup.py install

script: #"cd ..; nosetests --with-coverage --cover-package=nansat nansat.tests"
  coverage run --source=nansat setup.py test
after_success:
  coveralls
